<a href="https://colab.research.google.com/github/Azmal16/Deep_Learning_Specialization/blob/main/Neural%20Networks%20and%20Deep%20Learning/Broadcasting_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Calories from Carbs, Proteins and Fats of 100g of Apple, Beef, Eggss and Potatoes are given in matrix A.

In [7]:
import numpy as np
#Rows indicate the nutrition elements 
#Columns indicate the foods
A = np.array([[56.0, 0.0, 4.4, 68.0],
               [1.2, 104.0, 52.0, 8.0],
               [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


We sum the columns to get the total number of calories in each food in a form of a (1,4) Matrix

In [8]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


Percentage of calories provided by the nutrition elements of each food in a form of (3,4) Matrix without using explicit loops.

In [10]:
percentage = 100*A/(cal.reshape(1,4))
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
