<a href="https://colab.research.google.com/github/Azmal16/Deep_Learning_Specialization/blob/main/Neural%20Networks%20and%20Deep%20Learning/Python_Numpy_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.random.rand(5)
print(a)

[0.61822333 0.77923975 0.92170719 0.38865905 0.05246487]


In [ ]:
print(a.shape)

(5,)


In [ ]:
print(a.T)

[0.61822333 0.77923975 0.92170719 0.38865905 0.05246487]


In [ ]:
print(np.dot(a,a.T))

1.9927672345953604


In [ ]:
a = np.random.rand(5,1)
print(a)

[[0.74536133]
 [0.86912354]
 [0.73622898]
 [0.30560894]
 [0.20074705]]


In [ ]:
print(a.T)

[[0.74536133 0.86912354 0.73622898 0.30560894 0.20074705]]


In [ ]:
print(np.dot(a,a.T))

[[0.55556351 0.64781107 0.54875661 0.22778909 0.14962908]
 [0.64781107 0.75537572 0.63987394 0.26561192 0.17447398]
 [0.54875661 0.63987394 0.54203311 0.22499816 0.14779579]
 [0.22778909 0.26561192 0.22499816 0.09339682 0.06135009]
 [0.14962908 0.17447398 0.14779579 0.06135009 0.04029938]]
